import { useEffect, useState } from 'react'
import { BarChart3, BriefcaseBusiness, CreditCard, DollarSign, Landmark, Package, ReceiptText, TrendingUp, Users, Wallet } from 'lucide-react'
import { BarChart, Bar, LineChart, Line, CartesianGrid, XAxis, YAxis, Tooltip, ResponsiveContainer, PieChart, Pie, Cell, Legend } from 'recharts'
import StatCard from '../components/StatCard'
import { Button, Card, PageHeader, RefreshButton, Loading } from '../components/ui'
import Badge from '../components/Badge'
import { getDashboardSummary } from '../api/dashboard'
import { getAccounts } from '../api/accounts'
import { getContacts } from '../api/contacts'
import { getProducts } from '../api/products'
import { getJournalEntries } from '../api/journalEntries'
import { listify, money, pick, dateFmt } from '../utils'
import toast from 'react-hot-toast'
import { useNavigate } from 'react-router-dom'

export default function Dashboard(){const [summary,setSummary]=useState(null),[loading,setLoading]=useState(true),[meta,setMeta]=useState({accounts:[],contacts:[],products:[],entries:[]});const nav=useNavigate();
 const load=async()=>{setLoading(true);try{const [d,a,c,p,e]=await Promise.all([getDashboardSummary(),getAccounts(),getContacts(),getProducts(),getJournalEntries()]);setSummary(d||{});setMeta({accounts:listify(a),contacts:listify(c),products:listify(p),entries:listify(e).slice(-8).reverse()})}catch(err){toast.error(err.message)}finally{setLoading(false)}};useEffect(()=>{load()},[])
 const revenue=pick(summary,['revenue','total_revenue','sales','total_sales']);const expenses=pick(summary,['expenses','total_expenses','purchases','total_purchases']);const profit=pick(summary,['net_profit','profit']);const receivables=pick(summary,['receivables','accounts_receivable','total_receivables']);const payables=pick(summary,['payables','accounts_payable','total_payables']);const cash=pick(summary,['cash','cash_balance','total_cash']);const bank=pick(summary,['bank','bank_balance','total_bank']);
 const accountData=['ASSET','LIABILITY','INCOME','EXPENSE','CAPITAL'].map(t=>({name:t,value:meta.accounts.filter(a=>a.type===t).length})).filter(x=>x.value);const productData=['GOODS','SERVICE','COMBO'].map(t=>({name:t,value:meta.products.filter(p=>p.type===t).length})).filter(x=>x.value);const monthly=[{name:'Current',Revenue:Number(revenue),Expenses:Number(expenses),Profit:Number(profit)}];
 if(loading&&!summary)return <Loading/>;return <div><PageHeader title="Executive Dashboard" description="A live view of Urban Furniture's financial and operational pulse"><RefreshButton onClick={load} loading={loading}/><Button onClick={()=>nav('/sales')}>New Sale</Button></PageHeader>
 <div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-6 gap-4"><StatCard icon={TrendingUp} label="Revenue" value={money(revenue)} tone="cyan"/><StatCard icon={ReceiptText} label="Expenses" value={money(expenses)} tone="amber"/><StatCard icon={DollarSign} label="Net Profit" value={money(profit)} tone="emerald"/><StatCard icon={Users} label="Receivables" value={money(receivables)} tone="violet"/><StatCard icon={BriefcaseBusiness} label="Payables" value={money(payables)} tone="rose"/><StatCard icon={Wallet} label="Cash + Bank" value={money(Number(cash)+Number(bank))} tone="cyan"/></div>
 <div className="grid xl:grid-cols-3 gap-5 mt-5"><Card className="xl:col-span-2"><div className="flex items-center justify-between mb-5"><div><h3 className="font-bold text-slate-900 dark:text-white">Financial pulse</h3><p className="text-xs text-slate-400">Live values returned by the accounting API</p></div><Badge tone="green">LIVE API</Badge></div><div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={monthly}><CartesianGrid strokeDasharray="3 3" opacity={.15}/><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="Revenue" fill="#22d3ee" radius={[7,7,0,0]}/><Bar dataKey="Expenses" fill="#8b5cf6" radius={[7,7,0,0]}/><Bar dataKey="Profit" fill="#10b981" radius={[7,7,0,0]}/></BarChart></ResponsiveContainer></div></Card><Card><div className="flex items-center justify-between mb-3"><h3 className="font-bold text-slate-900 dark:text-white">Account mix</h3><Landmark size={18} className="text-cyan-400"/></div><div className="h-72"><ResponsiveContainer><PieChart><Pie data={accountData} dataKey="value" nameKey="name" cx="50%" cy="50%" outerRadius={88} innerRadius={58}>{accountData.map((x,i)=><Cell key={x.name} fill={['#22d3ee','#f43f5e','#10b981','#f59e0b','#8b5cf6'][i%5]}/>)}</Pie><Legend/><Tooltip/></PieChart></ResponsiveContainer></div></Card></div>
 <div className="grid xl:grid-cols-3 gap-5 mt-5"><Card className="xl:col-span-2"><div className="flex items-center justify-between mb-4"><div><h3 className="font-bold text-slate-900 dark:text-white">Recent journal activity</h3><p className="text-xs text-slate-400">Latest posted entries</p></div><Button variant="ghost" onClick={()=>nav('/journal-entries')}>View all</Button></div><div className="space-y-2">{meta.entries.length?meta.entries.map((e)=><div key={e.id} className="flex items-center justify-between px-3 py-3 rounded-xl hover:bg-black/[0.03] dark:hover:bg-white/[0.03]"><div><div className="text-sm font-semibold text-slate-800 dark:text-white">#{e.id} · {e.reference||'No reference'}</div><div className="text-xs text-slate-400">{dateFmt(e.entry_date)} · {e.description||'Journal entry'}</div></div><Badge tone="green">POSTED</Badge></div>):<div className="py-10 text-center text-sm text-slate-400">No journal entries yet.</div>}</div></Card><Card><div className="flex items-center justify-between mb-4"><div><h3 className="font-bold text-slate-900 dark:text-white">Catalog snapshot</h3><p className="text-xs text-slate-400">Active master data</p></div><Package size={18} className="text-violet-400"/></div><div className="space-y-3"><div className="flex justify-between"><span className="text-sm text-slate-500">Accounts</span><b>{meta.accounts.length}</b></div><div className="flex justify-between"><span className="text-sm text-slate-500">Contacts</span><b>{meta.contacts.length}</b></div><div className="flex justify-between"><span className="text-sm text-slate-500">Products</span><b>{meta.products.length}</b></div><div className="flex justify-between"><span className="text-sm text-slate-500">Journal entries</span><b>{meta.entries.length}</b></div></div><div className="mt-5 h-2 rounded-full bg-slate-200 dark:bg-white/10 overflow-hidden"><div className="h-full bg-gradient-to-r from-cyan-400 to-violet-500" style={{width:`${Math.min(100,meta.products.length*2)}%`}}/></div></Card></div></div>
}
