import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Sofa, ShieldCheck, Sparkles } from 'lucide-react'
import { useAuth } from '../context/AuthContext'
import { Button, Input } from '../components/ui'
import toast from 'react-hot-toast'

export default function Login(){const {login,loading}=useAuth();const nav=useNavigate();const [username,setUsername]=useState('admin');const [password,setPassword]=useState('admin123');
 const submit=async e=>{e.preventDefault();try{await login(username,password);toast.success('Welcome back');nav('/')}catch(err){toast.error(err.message)}}
 return <div className="min-h-screen flex items-center justify-center p-6 relative overflow-hidden"><div className="absolute -top-36 -left-36 w-96 h-96 rounded-full bg-cyan-500/20 blur-3xl"/><div className="absolute -bottom-36 -right-36 w-96 h-96 rounded-full bg-violet-600/20 blur-3xl"/><div className="w-full max-w-5xl grid lg:grid-cols-2 gap-8 items-center relative z-10"><div className="hidden lg:block"><div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full glass text-xs font-bold text-cyan-600 dark:text-cyan-300"><Sparkles size={14}/> ERP-grade accounting workspace</div><h1 className="font-display text-6xl font-black mt-5 text-slate-900 dark:text-white leading-[.95]">URBAN<br/><span className="gradient-text">FURNITURE.</span></h1><p className="mt-6 max-w-lg text-slate-500 dark:text-slate-400 text-lg">One place for sales, purchases, payments and double-entry accounting — built for modern furniture businesses.</p><div className="mt-8 flex gap-3"><div className="glass rounded-2xl p-4"><ShieldCheck className="text-emerald-400"/><div className="mt-2 text-sm font-bold">Accounting-first</div><div className="text-xs text-slate-400 mt-1">Balanced entries by design.</div></div><div className="glass rounded-2xl p-4"><Sparkles className="text-violet-400"/><div className="mt-2 text-sm font-bold">Live analytics</div><div className="text-xs text-slate-400 mt-1">Operational data in one view.</div></div></div></div><div className="glass-deep rounded-[30px] p-7 md:p-9 shadow-2xl"><div className="flex items-center gap-3"><div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-cyan-400 via-indigo-500 to-violet-600 flex items-center justify-center text-white shadow-lg"><Sofa size={23}/></div><div><div className="font-display font-black text-slate-900 dark:text-white">Urban Furniture</div><div className="text-[10px] tracking-[.18em] text-cyan-500 font-bold">ACCOUNTING 2026</div></div></div><h2 className="mt-8 text-3xl font-black text-slate-900 dark:text-white">Welcome back.</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Sign in to continue to your financial workspace.</p><form className="mt-7 space-y-4" onSubmit={submit}><Input label="Username" value={username} onChange={e=>setUsername(e.target.value)} required/><Input label="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)} required/><Button type="submit" className="w-full" disabled={loading}>{loading?'Signing in...':'Sign in'}</Button><button type="button" onClick={async()=>{try{await login('admin','admin123');nav('/')}catch(err){toast.error(err.message)}}} className="w-full px-4 py-3 rounded-xl glass text-sm font-semibold">Use demo account</button></form><div className="mt-6 text-[11px] text-slate-400">API: http://localhost:8001</div></div></div></div>
}
