import { useEffect, useMemo, useState } from 'react'
import { Edit3, Archive, Plus, Search, Package, Users, Landmark, BookOpen } from 'lucide-react'
import { useSearchParams } from 'react-router-dom'
import { Button, Card, Input, PageHeader, Select, Table, Modal, RefreshButton } from '../components/ui'
import Badge from '../components/Badge'
import { createAccount, updateAccount, archiveAccount, getAccounts } from '../api/accounts'
import { createContact, updateContact, archiveContact, getContacts } from '../api/contacts'
import { createProduct, updateProduct, archiveProduct, getProducts } from '../api/products'
import { createJournal, updateJournal, archiveJournal, getJournals } from '../api/journals'
import { money, listify, titleCase } from '../utils'
import toast from 'react-hot-toast'

const tones={ASSET:'cyan',LIABILITY:'rose',EXPENSE:'amber',INCOME:'green',CAPITAL:'violet',CUSTOMER:'cyan',VENDOR:'amber',BOTH:'violet',GOODS:'cyan',SERVICE:'amber',COMBO:'violet',SALES:'green',PURCHASE:'amber',BANK:'cyan',CASH:'violet'}
function MasterShell({title,description, icon:Icon, fetcher, create, update, archive, fields, mapForm, renderRow, placeholder}){
  const [data,setData]=useState([]),[loading,setLoading]=useState(true),[q,setQ]=useState(''),[open,setOpen]=useState(false),[editing,setEditing]=useState(null),[form,setForm]=useState(mapForm(null))
  const load=async()=>{setLoading(true);try{setData(listify(await fetcher()))}catch(e){toast.error(e.message)}finally{setLoading(false)}}
  useEffect(()=>{load()},[])
  const rows=useMemo(()=>data.filter(x=>JSON.stringify(x).toLowerCase().includes(q.toLowerCase())),[data,q])
  const submit=async e=>{e.preventDefault();try{const body=mapForm(form); if(editing) await update(editing.id,body); else await create(body);toast.success(editing?'Updated successfully':'Created successfully');setOpen(false);setEditing(null);load()}catch(e){toast.error(e.message)}}
  const edit=x=>{setEditing(x);setForm(mapForm(x));setOpen(true)}
  const remove=async x=>{if(!confirm(`Archive ${x.name||x.order_number||'this record'}?`))return;try{await archive(x.id);toast.success('Archived');load()}catch(e){toast.error(e.message)}}
  return <><PageHeader title={title} description={description} action={<Button icon={Plus} onClick={()=>{setEditing(null);setForm(mapForm(null));setOpen(true)}}>New</Button>}><RefreshButton onClick={load} loading={loading}/></PageHeader>
    <Card><div className="flex flex-col md:flex-row gap-3 mb-5"><div className="relative flex-1"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={placeholder||'Search...'} className="w-full pl-9 pr-3 py-2.5 rounded-xl bg-white/70 dark:bg-white/[0.04] border border-slate-200 dark:border-white/10 outline-none"/></div></div><Table columns={renderRow.columns} rows={rows} empty={loading?'Loading...':'No records found.'}/></Card>
    <Modal open={open} title={editing?`Edit ${title}`:`Create ${title}`} onClose={()=>setOpen(false)}>{<form onSubmit={submit} className="space-y-4">{fields.map(f=>f.type==='select'?<Select key={f.key} label={f.label} value={form[f.key]??''} onChange={e=>setForm({...form,[f.key]:e.target.value})} required={f.required}>{f.options.map(o=><option key={o[0]} value={o[0]}>{o[1]}</option>)}</Select>:<Input key={f.key} label={f.label} type={f.type||'text'} value={form[f.key]??''} onChange={e=>setForm({...form,[f.key]:e.target.value})} required={f.required} step={f.step} min={f.min}/>)}<div className="flex justify-end gap-2 pt-3"><Button variant="secondary" type="button" onClick={()=>setOpen(false)}>Cancel</Button><Button type="submit">{editing?'Save Changes':'Create'}</Button></div></form>}</Modal></>
}

export function Accounts(){return <MasterShell title="Chart of Accounts" description="Manage your double-entry account structure." icon={Landmark} fetcher={getAccounts} create={createAccount} update={updateAccount} archive={archiveAccount} placeholder="Search accounts..." mapForm={x=>({name:x?.name||'',type:x?.type||'ASSET'})} fields={[{key:'name',label:'Account name',required:true},{key:'type',label:'Account type',type:'select',required:true,options:[['ASSET','Asset'],['LIABILITY','Liability'],['EXPENSE','Expense'],['INCOME','Income'],['CAPITAL','Capital']]}]} renderRow={{columns:[{key:'id',label:'ID'},{key:'name',label:'Account'},{key:'type',label:'Type',render:x=><Badge tone={tones[x.type]}>{x.type}</Badge>},{key:'is_active',label:'Status',render:x=><Badge tone={x.is_active?'green':'red'}>{x.is_active?'Active':'Archived'}</Badge>}]}}/>}
export function Contacts(){return <MasterShell title="Contacts" description="Customers, vendors and partners in one directory." icon={Users} fetcher={getContacts} create={createContact} update={updateContact} archive={archiveContact} placeholder="Search contacts by name, email, phone or city..." mapForm={x=>({name:x?.name||'',type:x?.type||'CUSTOMER',email:x?.email||'',mobile:x?.mobile||'',city:x?.city||'',state:x?.state||'',pincode:x?.pincode||'',profile_image:x?.profile_image||''})} fields={[{key:'name',label:'Name',required:true},{key:'type',label:'Type',type:'select',required:true,options:[['CUSTOMER','Customer'],['VENDOR','Vendor'],['BOTH','Both']]},{key:'email',label:'Email',type:'email'},{key:'mobile',label:'Mobile'},{key:'city',label:'City'},{key:'state',label:'State'},{key:'pincode',label:'Pincode'},{key:'profile_image',label:'Profile image URL'}]} renderRow={{columns:[{key:'name',label:'Name'},{key:'type',label:'Type',render:x=><Badge tone={tones[x.type]}>{x.type}</Badge>},{key:'email',label:'Email',render:x=>x.email||'—'},{key:'mobile',label:'Mobile',render:x=>x.mobile||'—'},{key:'city',label:'City',render:x=>[x.city,x.state].filter(Boolean).join(', ')||'—'},{key:'is_active',label:'Status',render:x=><Badge tone={x.is_active?'green':'red'}>{x.is_active?'Active':'Archived'}</Badge>}]}}/>}
export function Products(){return <MasterShell title="Products & Services" description="Catalog your furniture, services and combo offerings." icon={Package} fetcher={getProducts} create={createProduct} update={updateProduct} archive={archiveProduct} placeholder="Search products, category or type..." mapForm={x=>({name:x?.name||'',type:x?.type||'GOODS',category:x?.category||'',sales_price:x?.sales_price??0,purchase_price:x?.purchase_price??0})} fields={[{key:'name',label:'Product name',required:true},{key:'type',label:'Type',type:'select',required:true,options:[['GOODS','Goods'],['SERVICE','Service'],['COMBO','Combo']]},{key:'category',label:'Category'},{key:'sales_price',label:'Sales price',type:'number',min:0,step:'0.01',required:true},{key:'purchase_price',label:'Purchase price',type:'number',min:0,step:'0.01',required:true}]} renderRow={{columns:[{key:'name',label:'Product'},{key:'type',label:'Type',render:x=><Badge tone={tones[x.type]}>{x.type}</Badge>},{key:'category',label:'Category',render:x=>x.category||'—'},{key:'sales_price',label:'Sales',render:x=>money(x.sales_price)},{key:'purchase_price',label:'Purchase',render:x=>money(x.purchase_price)},{key:'is_active',label:'Status',render:x=><Badge tone={x.is_active?'green':'red'}>{x.is_active?'Active':'Archived'}</Badge>}]}}/>}
export function Journals(){const [accounts,setAccounts]=useState([]);useEffect(()=>{getAccounts().then(setAccounts).catch(()=>{})},[]);return <MasterShell title="Journals" description="Configure operational daybooks and default posting accounts." icon={BookOpen} fetcher={getJournals} create={createJournal} update={updateJournal} archive={archiveJournal} placeholder="Search journals..." mapForm={x=>({name:x?.name||'',type:x?.type||'SALES',default_debit_account_id:x?.default_debit_account_id||'',default_credit_account_id:x?.default_credit_account_id||''})} fields={[{key:'name',label:'Journal name',required:true},{key:'type',label:'Type',type:'select',required:true,options:[['SALES','Sales'],['PURCHASE','Purchase'],['BANK','Bank'],['CASH','Cash']]},{key:'default_debit_account_id',label:'Default debit account',type:'select',required:true,options:accounts.map(a=>[a.id,`${a.id} — ${a.name}`])},{key:'default_credit_account_id',label:'Default credit account',type:'select',required:true,options:accounts.map(a=>[a.id,`${a.id} — ${a.name}`])}]} renderRow={{columns:[{key:'name',label:'Journal'},{key:'type',label:'Type',render:x=><Badge tone={tones[x.type]}>{x.type}</Badge>},{key:'default_debit_account_id',label:'Default Debit',render:x=>accounts.find(a=>a.id===x.default_debit_account_id)?.name||x.default_debit_account_id},{key:'default_credit_account_id',label:'Default Credit',render:x=>accounts.find(a=>a.id===x.default_credit_account_id)?.name||x.default_credit_account_id},{key:'is_active',label:'Status',render:x=><Badge tone={x.is_active?'green':'red'}>{x.is_active?'Active':'Archived'}</Badge>}]}}/>}
